const scannedOrdersData = [
    {
        order_number: '48048549452410',
        event_codes: [ 'EVT001', 'EVT002' ],
        full_name: 'John Doe',
        state_name: 'California',
        order_mode_name: 'Online',
        package_quantity: 2,
        is_digital: 'Yes',
        purchase_datetime: '01-11-2024',
        event_producer: 'EventCo',
        price: '$150',
        order_status: 1,
        is_toggle_on: true
    },
    {
        order_number: '48048549452411',
        event_codes: [ 'EVT003' ],
        full_name: 'Jane Smith',
        state_name: 'New York',
        order_mode_name: 'In-person',
        package_quantity: 1,
        is_digital: 'No',
        purchase_datetime: '02-11-2024',
        event_producer: 'ShowTime',
        price: '$75',
        order_status: 2,
        is_toggle_on: false
    },
    {
        order_number: '48048549452412',
        event_codes: [ 'EVT001', 'EVT002' ],
        full_name: 'John Doe',
        state_name: 'California',
        order_mode_name: 'Online',
        package_quantity: 2,
        is_digital: 'Yes',
        purchase_datetime: '03-11-2024',
        event_producer: 'EventCo',
        price: '$150',
        order_status: 1,
        is_toggle_on: true
    },
    {
        order_number: '48048549452413',
        event_codes: [ 'EVT003' ],
        full_name: 'Jane Smith',
        state_name: 'New York',
        order_mode_name: 'In-person',
        package_quantity: 1,
        is_digital: 'No',
        purchase_datetime: '04-11-2024',
        event_producer: 'ShowTime',
        price: '$75',
        order_status: 2,
        is_toggle_on: false
    },
    {
        order_number: 'ORD001',
        event_codes: [ 'EVT001', 'EVT002' ],
        full_name: 'John Doe',
        state_name: 'California',
        order_mode_name: 'Online',
        package_quantity: 2,
        is_digital: 'Yes',
        purchase_datetime: '05-11-2024',
        event_producer: 'EventCo',
        price: '$150',
        order_status: 1,
        is_toggle_on: true
    },
    {
        order_number: 'ORD002',
        event_codes: [ 'EVT003' ],
        full_name: 'Jane Smith',
        state_name: 'New York',
        order_mode_name: 'In-person',
        package_quantity: 1,
        is_digital: 'No',
        purchase_datetime: '07-11-2024',
        event_producer: 'ShowTime',
        price: '$75',
        order_status: 2,
        is_toggle_on: false
    },
    {
        order_number: 'ORD001',
        event_codes: [ 'EVT001', 'EVT002' ],
        full_name: 'John Doe',
        state_name: 'California',
        order_mode_name: 'Online',
        package_quantity: 2,
        is_digital: 'Yes',
        purchase_datetime: '10-11-2024',
        event_producer: 'EventCo',
        price: '$150',
        order_status: 1,
        is_toggle_on: true
    },
    {
        order_number: 'ORD002',
        event_codes: [ 'EVT003' ],
        full_name: 'Jane Smith',
        state_name: 'New York',
        order_mode_name: 'In-person',
        package_quantity: 1,
        is_digital: 'No',
        purchase_datetime: '11-11-2024',
        event_producer: 'ShowTime',
        price: '$75',
        order_status: 2,
        is_toggle_on: false
    },
    {
        order_number: 'ORD001',
        event_codes: [ 'EVT001', 'EVT002' ],
        full_name: 'John Doe',
        state_name: 'California',
        order_mode_name: 'Online',
        package_quantity: 2,
        is_digital: 'Yes',
        purchase_datetime: '01-11-2024',
        event_producer: 'EventCo',
        price: '$150',
        order_status: 1,
        is_toggle_on: true
    },
    {
        order_number: 'ORD002',
        event_codes: [ 'EVT003' ],
        full_name: 'Jane Smith',
        state_name: 'New York',
        order_mode_name: 'In-person',
        package_quantity: 1,
        is_digital: 'No',
        purchase_datetime: '01-11-2024',
        event_producer: 'ShowTime',
        price: '$75',
        order_status: 2,
        is_toggle_on: false
    },
    {
        order_number: 'ORD001',
        event_codes: [ 'EVT001', 'EVT002' ],
        full_name: 'John Doe',
        state_name: 'California',
        order_mode_name: 'Online',
        package_quantity: 2,
        is_digital: 'Yes',
        purchase_datetime: '01-11-2024',
        event_producer: 'EventCo',
        price: '$150',
        order_status: 1,
        is_toggle_on: true
    },
    {
        order_number: 'ORD002',
        event_codes: [ 'EVT003' ],
        full_name: 'Jane Smith',
        state_name: 'New York',
        order_mode_name: 'In-person',
        package_quantity: 1,
        is_digital: 'No',
        purchase_datetime: '01-11-2024',
        event_producer: 'ShowTime',
        price: '$75',
        order_status: 2,
        is_toggle_on: false
    },
    {
        order_number: 'ORD001',
        event_codes: [ 'EVT001', 'EVT002' ],
        full_name: 'John Doe',
        state_name: 'California',
        order_mode_name: 'Online',
        package_quantity: 2,
        is_digital: 'Yes',
        purchase_datetime: '01-11-2024',
        event_producer: 'EventCo',
        price: '$150',
        order_status: 1,
        is_toggle_on: true
    },
    {
        order_number: 'ORD002',
        event_codes: [ 'EVT003' ],
        full_name: 'Jane Smith',
        state_name: 'New York',
        order_mode_name: 'In-person',
        package_quantity: 1,
        is_digital: 'No',
        purchase_datetime: '01-11-2024',
        event_producer: 'ShowTime',
        price: '$75',
        order_status: 2,
        is_toggle_on: false
    },
    {
        order_number: 'ORD001',
        event_codes: [ 'EVT001', 'EVT002' ],
        full_name: 'John Doe',
        state_name: 'California',
        order_mode_name: 'Online',
        package_quantity: 2,
        is_digital: 'Yes',
        purchase_datetime: '01-11-2024',
        event_producer: 'EventCo',
        price: '$150',
        order_status: 1,
        is_toggle_on: true
    },
    {
        order_number: 'ORD002',
        event_codes: [ 'EVT003' ],
        full_name: 'Jane Smith',
        state_name: 'New York',
        order_mode_name: 'In-person',
        package_quantity: 1,
        is_digital: 'No',
        purchase_datetime: '01-11-2024',
        event_producer: 'ShowTime',
        price: '$75',
        order_status: 2,
        is_toggle_on: false
    },
];

export default scannedOrdersData;