export const staffList = [
  {
    key: "1",
    name: "Mike",
    age: 32,
    address: "10 Downing Street",
    phoneNo: "N/A",
    staffName: "Mike",
    trueId: "REJECTED",
    rating: "5",
    category: "Employee",
    score: "450/500",
    isRecommended: true,
  },
  {
    key: "2",
    name: "John",
    age: 42,
    address: "10 Downing Street",
    phoneNo: "N/A",
    staffName: "John",
    trueId: "VERIFIED",
    rating: "5",
    category: "Employee",
    score: "450/500",
    isRecommended: true,
  },
  {
    key: "3",
    name: "Sarah",
    age: 29,
    address: "221B Baker Street",
    phoneNo: "+1 123 456 7890",
    staffName: "Sarah",
    trueId: "REJECTED",
    rating: "4.5",
    category: "Manager",
    score: "450/500",
    isRecommended: true,
  },
  {
    key: "4",
    name: "Emma",
    age: 35,
    address: "1600 Pennsylvania Avenue",
    phoneNo: "+1 234 567 8901",
    staffName: "Emma",
    trueId: "VERIFIED",
    rating: "5",
    category: "Employee",
    score: "450/500",
    isRecommended: true,
  },
  {
    key: "5",
    name: "David",
    age: 40,
    address: "742 Evergreen Terrace",
    phoneNo: "+44 7890 123456",
    staffName: "David",
    trueId: "VERIFIED",
    rating: "4",
    category: "Supervisor",
    score: "450/500",
    isRecommended: true,
  },
  {
    key: "6",
    name: "Lucy",
    age: 30,
    address: "12 Grimmauld Place",
    phoneNo: "+1 345 678 9012",
    staffName: "Lucy",
    trueId: "PENDING",
    rating: "5",
    category: "Employee",
    score: "450/500",
    isRecommended: true,
  },
  {
    key: "7",
    name: "Mark",
    age: 28,
    address: "4 Privet Drive",
    phoneNo: "+44 1234 567890",
    staffName: "Mark",
    trueId: "VERIFIED",
    rating: "4",
    category: "Employee",
    score: "450/500",
    isRecommended: false,
  },
  {
    key: "8",
    name: "Sophia",
    age: 26,
    address: "Buckingham Palace",
    phoneNo: "+44 7890 234567",
    staffName: "Sophia",
    trueId: "PENDING",
    rating: "5",
    category: "VERIFIED",
    score: "450/500",
    isRecommended: false,
  },
  {
    key: "9",
    name: "Liam",
    age: 31,
    address: "The White House",
    phoneNo: "+1 567 890 1234",
    staffName: "Liam",
    trueId: "PENDING",
    rating: "4.5",
    category: "Manager",
    score: "450/500",
    isRecommended: false,
  },
  {
    key: "10",
    name: "Olivia",
    age: 33,
    address: "10 Downing Street",
    phoneNo: "+44 5678 901234",
    staffName: "Olivia",
    trueId: "PENDING",
    rating: "5",
    category: "Employee",
    score: "450/500",
    isRecommended: false,
  },
];

export const staffHeaders = [
  {
    key: "staffName",
    value: "Name",
    sortable: false,
    filter: false,
    type: "TEXT",
  },
  {
    key: "address",
    value: "Location",
    sortable: false,
    filter: false,
    type: "TEXT",
  },
  {
    key: "score",
    value: "Profile Score",
    sortable: false,
    filter: false,
    type: "PROFILE_SCORE",
  },
  {
    key: "rating",
    value: "Saathi Rating",
    sortable: false,
    filter: false,
    type: "RATING",
  },
  {
    key: "category",
    value: "Category",
    sortable: false,
    filter: false,
    type: "TEXT",
  },
];

export const pricingPlans = [
  {
    credits: "2000 C",
    price: "2,000 only",
    validityText: "6 months ",
    benefitsText: null,
    recommended: false,
  },
  {
    credits: "5750 C",
    price: "5,000 only",
    validityText: "9 months ",
    benefitsText: "15% EXTRA CREDITS",
    recommended: true,
  },
  {
    credits: "12000 C",
    price: "10,000 only",
    validityText: "12 months ",
    benefitsText: "20% EXTRA CREDITS",
    recommended: false,
  },
];
