export const ENDPOINTS = Object.freeze({
  getAllCourses: '/lms/api/v1/curriculum/course/all',
  postAddCourse: '/lms/api/v1/curriculum/course',
  courseDetails: (id) => `/lms/api/v1/curriculum/course/${id}`,
  uploadcsv: (id) => `/lms/api/v1/curriculum/course/uploadcsv/${id}`,
  courseAssessment: '/lms/api/v1/curriculum/courseAssessment',
  editCourseModule: (id) => `/lms/api/v1/curriculum/courseModule/${id}`,
  editCourseSubModule: (id) => `/lms/api/v1/curriculum/courseSubModule/${id}`,
  editCourseAssessment: (id) => `/lms/api/v1/curriculum/courseAssessment/${id}`,
  getAllPayments: `/payment/api/v1`,
  getRefundPayments: `/order/api/v1/refund`,
  refundPaymentDetails: (id) => `/order/api/v1/refund/${id}`,
  paymentDetails: (id) => `/payment/api/v1/${id}`,
  getAllOrders: `/order/api/v1`,
  getOrderDetails: (id) => `/order/api/v1/internal/${id}`,
  getCustomerPayments: (id) => `/payment/api/v1/user/${id}`,
  getCustomerOrders: (id) => `/order/api/v1/user/${id}`,
  getCustomerCourses: (id) =>
    `/customerJourney/api/v1/journey/dash/myTrainings/${id}`,
  getAllCustomers: '/customer/api/v1/',
  getAllApplicants: '/customer/api/v1',
  getAllInterviews: '/interview/api/v1/dash/getInterviewsForDashboard',
  customerDetails: (id) => `/customer/api/v1/${id}`,
  putCustomerDetails: `/customer/api/v1/update`,
  postIdentity: `/identity/api/v1/guest`,
  postVerifyPassword: `/user/api/V1/login/verify/password`,
  uploadToS3: (filePath, type, bucket) =>
    `/utils/api/v1/aws/uploadFile?filePath=${filePath}&type=${type}${bucket ? `&bucket=${bucket}` : ''}`,
  postEditPsychWeightage:
    '/lms/api/v1/curriculum/course/psychometric-trait-weightage',
  getGlobalData: `/lms/api/v1/curriculum/course/data`,
  getGlobalDataByName: (name) => `/global/api/v1/data?name=${name}`,
  getUserDetails: (userId) => `/user/api/v1?id=${userId}`,
  putResetPassword: '/user/api/v1/password',
  postRemarks: `/customer/api/v1/trueIdRemark/create/remark`,
  putUpdateTrueId: `/customer/api/v1/trueId`,
  postSendSms: `/customer/api/v1/trueId/verification/sms`,
  putUpdateCustomer: `/customer/api/v1/update/`,
  getReferrerDetails: (id) =>
    `/referral/api/v1/referral/details?referrerUserId=${id}`,
  getReferralHistory: (id, userType) =>
    `/referral/api/v1/referral/orderHistory?referrerUserId=${id}&userType=${userType}`,
  getAllUsers: `/user/api/v1/getAll`,
  getAllRoles: `/authorization/api/v1/role/getAll`,
  getAllPermissions: `/authorization/api/v1/permission/getAll`,
  postUserRole: `/authorization/api/v1/role`,
  putOrDeleteUserRole: (id) => `/authorization/api/v1/role/${id}`,
  postAddUser: `/user/api/v1/create/ops`,
  putUpdateUser: (id) => `/user/api/v1?id=${id}`,
  deleteUser: (id) => `/user/api/v1/${id}`,
  postUserPermission: `/authorization/api/v1/permission`,
  putOrDeleteUserPermission: (id) => `/authorization/api/v1/permission/${id}`,
  getAllTests: `/test/api/v1/tests`,
  getTestDetails: (id) => `/test/api/v1/tests/${id}`,
  uploadTestCsv: (id) => `/test/api/v1/tests/uploadcsv/${id}`,
  postAddTest: `/test/api/v1/tests/create`,
  putOrDeleteTest: (id) => `/test/api/v1/tests/${id}`,
  putUpdateTestAssessment: `/test/api/v1/tests/updateAssessment`,
  getTestCategories: `/test/api/v1/tests/getCategories`,
  getEmpReferrerDetails: (id) =>
    `/referral/api/v1/referral/refereeDetails?parentReferrerUserId=${id}`,
  getEmpReferrerEarnDetails: (id, type) =>
    `/referral/api/v1/referral/refereeDetails?parentReferrerUserId=${id}&expandLevel1Details=${type}`,
  getEmpCandidateReferrerEarnDetails: (id, candidateId, type) =>
    `/referral/api/v1/referral/refereeDetails?parentReferrerUserId=${id}&targetChildReferrerUserId=${candidateId}&expandLevel1Details=${type}`,
  getAllPayouts: `/staffingAgency/api/v1/payoutRequests`,
  getPayoutDetails: (id) => `/staffingAgency/api/v1/payout/${id}`,
  changePayoutStatus: (id) => `/staffingAgency/api/v1/${id}/changePayoutStatus`,
  getEmployerDetails: (id) => `/staffingAgency/api/v1/${id}`,
  employerDocPostRemarks: `/staffingAgency/api/v1/staffingAgencyRemark/create/remark`,
  putUpdateEmployerStatus: (id) => `/staffingAgency/api/v1/?id=${id}`,
  getAllEmployer: `/staffingAgency/api/v1`,
  getAllStaff: `/staffingAgency/api/v1/staffCustomers`,
  getEmployerJobs: `/staffingAgency/api/v1/job/`,
  getEarnings: `/referral/api/v1/earning`,
  postInitiateRefund: (id) => `/order/api/v1/refund/${id}`,
  putPanDetails: `/customer/api/v1/hyperVerge/upload/pan`,
  getRefreshToken: `/identity/api/v1/refreshToken/getNewAccessAndRefreshToken`,
  trueIDDetails: `/customer/api/v1/trueId/`,
  postAddJob: '/staffingAgency/api/v1/job',
  getWebsiteDomainVerification: (domain) =>
    `/staffingAgency/api/v1/checkValidDomain?domain=${domain}`,
  getGlobalEmployerData: `/global/api/v1/data?name=EMPLOYER_CREATION_HEADERS`,
  getJobById: (id) => `/staffingAgency/api/v1/job/${id}`,
  getJobCategories: `/global/api/v1/data?name=JOB_CATEGORY_AND_SALARY_RANGES`,
  getApplicantDetails: (id) =>
    `/customer/api/v1/jobs/getApplicationDetails?customerJobId=${id}`,
  putApplicantStatus: (id) =>
    `/customer/api/v1/jobs/updateStatus?customerJobId=${id}`,
  getAllApplications: `/customer/api/v1/jobs/getAllJobApplications`,
  getCityStateByPincode: (pincode) =>
    `/utils/api/v1/stateCity?pincode=${pincode}`,
  getUserBasicDetails: (id) => `/customer/api/v1/profile?customerId=${id}`,
  getCompanyDetailsByDocumentNo: `/customer/api/v1/hyperverge/verifyDocument`,
  getCustomerDeviceInfo: (userId) => `/user/api/v1/deviceInfo?userId=${userId}`,
  getCustomerLoggedInMobileInfo: (macAddress) =>
    `/identity/api/v1/guest/customerData?macAddress=${macAddress}`,
  putCustomerUnblockStatus: `/user/api/v1/unBlockUser`,
  putDeviceUnblockStatus: `/identity/api/v1/unBlockIdentity`,
  downloadEmployerJobs: `/staffingAgency/api/v1/job/`,
  putUpdateCustomerProfile: `/customer/api/v1/profile`,
  getTrueIdStaticData: '/global/api/v1/data?name=TRUEID_STATIC_DATA',
  getJobReelGlobalData: '/customer/api/v1/jobReel/data',
  postCreditsPackageData: (employerId, productId) =>
    `/order/api/v1/employer/${employerId}/package/offline/${productId}`,
  getSubscriptionData:
    '/staffingAgency/api/v1/employer/packagesAndSubscription',
  getLedgerData: '/staffingAgency/api/v1/employer/ledgerOps',
  getAllCustomerApplications:
    '/customer/api/v1/jobs/getAllCustomerApplications',
  campaignDetails: `/utils/api/v1/campaign`,
  uploadCampaignsCsv: `/utils/api/v1/campaign/bulk`,
  getAutoSuggestedData: (jobreelId) =>
    `/customer/api/v1/jobReel/autosuggestions/${jobreelId}`,
});
