export const JOB_EVENTS = {
  EMPLOGIN_PHNNUM_ENTERED: "emplogin_phnNum_Entered",
  EMPLOGIN_MEMBERSHIPCTA_CLICK: "emplogin_MembershipCTA_Click",
  PAYMENT_PAYCTA_CLICK: "payment_PayCTA_Click",
  PAYMENT_TC_CLICK: "payment_T&C_Click",
  PAYMENT_UPIID_ENTERED: "payment_UpiID_Entered",
  PAYMENT_INVALIDUPI_ERROR: "payment_InvalidUPI_Error",
  PAYMENT_PROCESSING_VIEWED: "payment_Processing_viewed",
  PAYMENT_CONFIRMATION_VIEWED: "payment_Confirmation_viewed",
  PAYMENT_REJECTION_VIEWED: "payment_Rejection_viewed",
  PAYMENT_PAGE_LOAD: "payment_Page_Load",
  EMPLOGIN_SENDOTP_CLICK: "emplogin_SendOtp_Click",
  EMPLOGIN_TANDC_CLICK: "emplogin_T&C_Click",
  EMPLOGIN_PRIVPOLICY_CLICK: "emplogin_PrivPolicy_Click",
  EMPLOGIN_ENTEROTP: "emplogin_EnterOtp",
  EMPLOGIN_SUBMITOTP_CLICK: "emplogin_SubmitOtp_Click",
  EMPLOGIN_WRONGOTP: "emplogin_WrongOtp",
  EMPLOGIN_RESENDOTP_CLICK: "emplogin_ResendOtp_Click",
  EMPLOGIN_EMPTYPE_CLICK: "emplogin_EmpType_Click",
  EMPLOGIN_EMPNAME_ENTERED: "emplogin_EmpName_Entered",
};
